version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db_service
    environment:
      - ConnectionStrings__Db=Server=db_service;Port=5432;Database=TestDb;User ID=postgres;Password=12345;IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - test_network

  db_service:
    image: postgres:15
    restart: always
    container_name: db_service
    environment:
      POSTGRES_DB: TestDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - test_network

networks:
    test_network:
        driver: bridge
volumes:
    data: